# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.1
    hooks:
    -   id: sync-pre-commit-deps
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-ast
    -   id: check-toml
    -   id: check-shebang-scripts-are-executable
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: mixed-line-ending
-   repo: https://github.com/crate-ci/typos
    rev: v1.26.0
    hooks:
      - id: typos

-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell

-   repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.24
    hooks:
    -   id: pymarkdown

-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.3
    hooks:
      - id: actionlint

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.0
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
        types: [executable]
        # files: ^bin/ # only if we need to limit it to the bin folder

-   repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
    -   id: bashate
        types: [executable]
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    -   id: pyupgrade
