# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# With this line, "pre-commit install" will install the most common hook types
default_install_hook_types: [pre-commit, pre-push, commit-msg]

repos:
-   repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.1
    hooks:
    -   id: sync-pre-commit-deps
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-ast
    -   id: check-toml
    -   id: check-shebang-scripts-are-executable
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: mixed-line-ending
    -   id: debug-statements
-   repo: https://github.com/crate-ci/typos
    rev: typos-dict-v0.11.35
    hooks:
      - id: typos

-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    - id: codespell

-   repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.25
    hooks:
    -   id: pymarkdown

-   repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.30.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [pre-push]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.3
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
        types: [executable]
        # files: ^bin/ # only if we need to limit it to the bin folder

-   repo: https://github.com/openstack/bashate
    rev: 2.1.1
    hooks:
    -   id: bashate
        types: [executable]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    -   id: pyupgrade

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy

-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.13'  # or any later Vulture version
    hooks:
      - id: vulture

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    -   id: pyupgrade
        args: [--py313-plus]

-   repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
    -   id: checkmake

-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.21.2
    hooks:
      - id: gitleaks

-   repo: https://github.com/thoughtworks/talisman
    rev: 'v1.32.0'  # Update me!
    hooks:
      # both pre-commit and pre-push supported
      # -   id: talisman-push
      - id: talisman-commit
        entry: cmd --githook pre-commit
