[project]
name = "rest-api-django"
version = "0.1.0"
description = "A project that builds a Django based REST API from scratch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.uv]
dev-dependencies = [
    "pre-commit>=4.0.1",
]
